workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "dev"'

stages:
  - build
  - lint_format
  - migrations
  # - tests
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV} docker/.env
  script:
    - docker build -f docker/Dockerfile -t clear-talk-image .

lint-job:
  stage: lint_format
  script:
    - docker run --rm clear-talk-image make lint

format-job:
  stage: lint_format
  script:
    - docker run --rm clear-talk-image make format

# tests-job:
#   stage: tests
#   script:
#     - docker run --rm --network clear-talk-network clear-talk-image make test

migrations-job:
  stage: migrations
  script:
    - docker run --rm --network clear-talk-network clear-talk-image make alembic
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy-job:
  stage: deploy
  script:
    - docker compose -f docker/docker-compose-ci.yml up --build -d
    - docker image prune -f
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
