services:

  clear-talk:
    container_name: 'clear-talk'
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - clear-talk-network
    volumes:
      - /var/log/clear-talk/:/app/logs/

networks:
  clear-talk-network:
    external: True

volumes:
  clear-talk-pgdata:
