services:

  clear-talk:
    container_name: 'clear-talk'
    image: clear-talk-image:latest
    restart: unless-stopped
    networks:
      - clear-talk-network
    volumes:
      - /var/log/clear-talk/:/app/logs/

networks:
  clear-talk-network:
    external: True
