services:

  clear-talk:
    container_name: 'clear-talk'
    image: clear-talk-image:latest
    restart: unless-stopped
    networks:
      - clear-talk-network

networks:
  clear-talk-network:
    external: True
